version: "3.9"

services:
  app:
    build:
      args:
        user: exp_user
        uid: 1000
      context: ./
      dockerfile: .docker/Dockerfile
    image: expenses
    container_name: expenses-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - expenses
  mysql:
    image: library/mysql:latest
    container_name: expenses-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MSQL_USER=${DB_USERNAME}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - expenses
  nginx:
    image: library/nginx:1.17-alpine
    container_name: expenses-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      - expenses

networks:
  expenses:
    driver: bridge

volumes:
  mysql:
    driver: "local"
